export const staffList = [
  {
    id: 1,
    name: "Cameron Williamson",
    role: "Doctor",
    day: "Monday - Morning",
    time: "Sep 12 08:00 AM - Sep 13 16:00 PM",
  },
  {
    id: 2,
    name: "Wade Warren",
    role: "Doctor",
    day: "Monday - Morning",
    time: "Sep 12 08:00 AM - Sep 13 16:00 PM",
  },
  {
    id: 3,
    name: "Brooklyn Simmons",
    role: "Doctor",
    day: "Monday - Morning",
    time: "Sep 12 08:00 AM - Sep 13 16:00 PM",
  },
  {
    id: 4,
    name: "Leslie Alexander",
    role: "Doctor",
    day: "Monday - Morning",
    time: "Sep 12 08:00 AM - Sep 13 16:00 PM",
  },
  {
    id: 5,
    name: "Guy Hawkins",
    role: "Doctor",
    day: "Monday - Morning",
    time: "Sep 12 08:00 AM - Sep 13 16:00 PM",
  },
  {
    id: 6,
    name: "Robert Fox",
    role: "Doctor",
    day: "Monday - Morning",
    time: "Sep 12 08:00 AM - Sep 13 16:00 PM",
  },
  {
    id: 7,
    name: "Jacob Jones",
    role: "Doctor",
    day: "Monday - Morning",
    time: "Sep 12 08:00 AM - Sep 13 16:00 PM",
  },
  {
    id: 8,
    name: "Kristin Watson",
    role: "Doctor",
    day: "Monday - Morning",
    time: "Sep 12 08:00 AM - Sep 13 16:00 PM",
  },
  {
    id: 9,
    name: "Ronald Richards",
    role: "Doctor",
    day: "Monday - Morning",
    time: "Sep 12 08:00 AM - Sep 13 16:00 PM",
  },
  {
    id: 10,
    name: "Ralph Edwards",
    role: "Doctor",
    day: "Monday - Morning",
    time: "Sep 12 08:00 AM - Sep 13 16:00 PM",
  },
  {
    id: 11,
    name: "Darlene Robertson",
    role: "Doctor",
    day: "Monday - Morning",
    time: "Sep 12 08:00 AM - Sep 13 16:00 PM",
  },
  {
    id: 12,
    name: "Floyd Miles",
    role: "Doctor",
    day: "Monday - Morning",
    time: "Sep 12 08:00 AM - Sep 13 16:00 PM",
  },
  {
    id: 13,
    name: "Courtney Henry",
    role: "Doctor",
    day: "Monday - Morning",
    time: "Sep 12 08:00 AM - Sep 13 16:00 PM",
  },
  {
    id: 14,
    name: "Theresa Webb",
    role: "Doctor",
    day: "Monday - Morning",
    time: "Sep 12 08:00 AM - Sep 13 16:00 PM",
  },
  {
    id: 15,
    name: "Kathryn Murphy",
    role: "Doctor",
    day: "Monday - Morning",
    time: "Sep 12 08:00 AM - Sep 13 16:00 PM",
  },
  {
    id: 16,
    name: "Eleanor Pena",
    role: "Doctor",
    day: "Monday - Morning",
    time: "Sep 12 08:00 AM - Sep 13 16:00 PM",
  },
];

//All Generated Invoices data:

import greenIcon from "./src/assets/images/greenIcon.png";
import redIcon from "./src/assets/images/redIcon.png";

export const paymentReceipt = [
  {
    icon: greenIcon,
    date: "4/4/18 12:30AM",
    paymentInfo: "Payment For Treatment: Mr John Doings",
    price: "N100,000",
    status: "Successful",
  },
  {
    icon: greenIcon,
    date: "4/4/18 12:30AM",
    paymentInfo: "Payment For Treatment: Mr John Doings",
    price: "N100,000",
    status: "Successful",
  },
  {
    icon: greenIcon,
    date: "4/4/18 12:30AM",
    paymentInfo: "Payment For Treatment: Mr John Doings",
    price: "N100,000",
    status: "Successful",
  },
  {
    icon: greenIcon,
    date: "4/4/18 12:30AM",
    paymentInfo: "Payment For Treatment: Mr John Doings",
    price: "N100,000",
    status: "Successful",
  },
  {
    icon: redIcon,
    date: "4/4/18 12:30AM",
    paymentInfo: "Payment For Treatment: Mr John Doings",
    price: "N100,000",
    status: "Failed",
  },
  {
    icon: redIcon,
    date: "4/4/18 12:30AM",
    paymentInfo: "Payment For Treatment: Mr John Doings",
    price: "N100,000",
    status: "Failed",
  },
];

//All Generated Invoices data ends here
export const pharmacyData = [
  {
    id: 1,
    name: "Amoxicillin 500mg",
    category: "pain-relieving",
    stock: 20,
    vendor: "NPRR",
    status: "In Stock",
    price: "₦5000",
  },
  {
    id: 2,
    name: "Paracetamol 650mg",
    category: "pain-relieving",
    stock: 20,
    vendor: "NPRR",
    status: "Out of Stock",
    price: "₦6000",
  },
  {
    id: 3,
    name: "Insulin dosage",
    category: "pain-relieving",
    stock: 20,
    vendor: "NPRR",
    status: "Low Stock",
    price: "₦3000",
  },
  {
    id: 4,
    name: "Vitamin C 1000mg",
    category: "pain-relieving",
    stock: 20,
    vendor: "NPRR",
    status: "Low Stock",
    price: "₦6000",
  },
  {
    id: 5,
    name: "Omeprazole 20mg",
    category: "pain-relieving",
    stock: 20,
    vendor: "NPRR",
    status: "In Stock",
    price: "₦4000",
  },
  {
    id: 6,
    name: "Lisinopril 10mg",
    category: "pain-relieving",
    stock: 20,
    vendor: "NPRR",
    status: "In Stock",
    price: "₦2000",
  },
  {
    id: 7,
    name: "Atorvastatin 20mg",
    category: "pain-relieving",
    stock: 20,
    vendor: "NPRR",
    status: "Out of Stock",
    price: "₦5000",
  },
  {
    id: 8,
    name: "Ketoprofen",
    category: "pain-relieving",
    stock: 20,
    vendor: "NPRR",
    status: "Out of Stock",
    price: "₦3000",
  },
];

export const laboratoryData = [
  {
    id: 1,
    name: "Tobi test",
    category: "pain-relieving",
    stock: 20,
    vendor: "NPRR",
    status: "In Stock",
    price: "₦5000",
  },
  {
    id: 2,
    name: "HIV test",
    category: "pain-relieving",
    stock: 20,
    vendor: "NPRR",
    status: "Out of Stock",
    price: "₦6000",
  },
  {
    id: 3,
    name: "ulcer dosage",
    category: "pain-relieving",
    stock: 20,
    vendor: "NPRR",
    status: "Low Stock",
    price: "₦3000",
  },
  {
    id: 4,
    name: "testosterone 1000mg",
    category: "pain-relieving",
    stock: 20,
    vendor: "NPRR",
    status: "Low Stock",
    price: "₦6000",
  },
  {
    id: 5,
    name: "kidney test 20mg",
    category: "pain-relieving",
    stock: 20,
    vendor: "NPRR",
    status: "In Stock",
    price: "₦4000",
  },
  {
    id: 6,
    name: "Sugar test 10mg",
    category: "pain-relieving",
    stock: 20,
    vendor: "NPRR",
    status: "In Stock",
    price: "₦2000",
  },
  {
    id: 7,
    name: "Sugury test 20mg",
    category: "pain-relieving",
    stock: 20,
    vendor: "NPRR",
    status: "Out of Stock",
    price: "₦5000",
  },
  {
    id: 8,
    name: "HIV test",
    category: "pain-relieving",
    stock: 20,
    vendor: "NPRR",
    status: "Out of Stock",
    price: "₦3000",
  },
];

//NURSE DATA FOR INCOMING PATIENT IN NURSE DASHBOARD
export const incomingData = [
  {
    name: " Leslie Alexander",
    insurance: "Self-pay",
    PatientID: "P-2025-002",
    illness: "Fever and cough",
    Alert: "Severe shellfish allergy",
    medicalOption1: "Accept",
    medicalOption2: "Record vital",
    medicalOption3: "Send to Doctor",
    registered: "09:45 AM",
  },
  {
    name: " Leslie Alexander",
    insurance: "Self-pay",
    PatientID: "P-2025-002",
    illness: "Fever and cough",
    Alert: "Severe shellfish allergy",
    medicalOption1: "Accept",
    medicalOption2: "Record vital",
    medicalOption3: "Send to Doctor",
    registered: "09:45 AM",
  },
  {
    name: " Leslie Alexander",
    insurance: "Self-pay",
    PatientID: "P-2025-002",
    illness: "Fever and cough",
    Alert: "Severe shellfish allergy",
    medicalOption1: "Accept",
    medicalOption2: "Record vital",
    medicalOption3: "Send to Doctor",
    registered: "09:45 AM",
  },
  {
    name: " Leslie Alexander",
    insurance: "Self-pay",
    PatientID: "P-2025-002",
    illness: "Fever and cough",
    Alert: "Severe shellfish allergy",
    medicalOption1: "Accept",
    medicalOption2: "Record vital",
    medicalOption3: "Send to Doctor",
    registered: "09:45 AM",
  },
  {
    name: " Leslie Alexander",
    insurance: "Self-pay",
    PatientID: "P-2025-002",
    illness: "Fever and cough",
    Alert: "Severe shellfish allergy",
    medicalOption1: "Accept",
    medicalOption2: "Record vital",
    medicalOption3: "Send to Doctor",
    registered: "09:45 AM",
  },
  {
    name: " Leslie Alexander",
    insurance: "Self-pay",
    PatientID: "P-2025-002",
    illness: "Fever and cough",
    Alert: "Severe shellfish allergy",
    medicalOption1: "Accept",
    medicalOption2: "Record vital",
    medicalOption3: "Send to Doctor",
    registered: "09:45 AM",
  },
  {
    name: " Leslie Alexander",
    insurance: "Self-pay",
    PatientID: "P-2025-002",
    illness: "Fever and cough",
    Alert: "Severe shellfish allergy",
    medicalOption1: "Accept",
    medicalOption2: "Record vital",
    medicalOption3: "Send to Doctor",
    registered: "09:45 AM",
  },
  {
    name: " Leslie Alexander",
    insurance: "Self-pay",
    PatientID: "P-2025-002",
    illness: "Fever and cough",
    Alert: "Severe shellfish allergy",
    medicalOption1: "Accept",
    medicalOption2: "Record vital",
    medicalOption3: "Send to Doctor",
    registered: "09:45 AM",
  },
];

//NURSE DASHBOARD PATIENT SIDEBAR DATA
export const patients = [
  {
    name: "Jane Cooper",
    gender: "F",
    age: 36,
    blood: "A+",
    diagnosis: "Hepatitis B",
    phone: "(217) 555-0113",
    address: "6391 Elgin St. Celina, Delaware 10299",
    status: "Active",
  },
  {
    name: "Theresa Webb",
    gender: "F",
    age: 36,
    blood: "A-",
    diagnosis: "Hepatitis B",
    phone: "(207) 555-0119",
    address: "2118 Thornridge Syracuse, 35624",
    status: "Not Active",
  },
  {
    name: "Albert Flores",
    gender: "F",
    age: 36,
    blood: "B+",
    diagnosis: "Hepatitis B",
    phone: "(217) 555-0113",
    address: "3891 Ranchview Richardson,California",
    status: "Active",
  },
  {
    name: "Robert Fox",
    gender: "M",
    age: 36,
    blood: "AB+",
    diagnosis: "Hepatitis B",
    phone: "(480) 555-0103",
    address: "3891 Ranchview Richardson,California",
    status: "Passaway",
  },
  {
    name: "Savannah Nguyen",
    gender: "F",
    age: 36,
    blood: "AB+",
    diagnosis: "Hepatitis B",
    phone: "(209) 555-0104",
    address: "6391 Elgin St. Celina, Delaware 10299",
    status: "Active",
  },
  {
    name: "Annette Black",
    gender: "F",
    age: 36,
    blood: "AB-",
    diagnosis: "Hepatitis B",
    phone: "(225) 555-0118",
    address: "2118 Thornridge Syracuse, 35624",
    status: "Active",
  },
  {
    name: "Robert Fox",
    gender: "M",
    age: 36,
    blood: "O+",
    diagnosis: "Hepatitis B",
    phone: "(270) 555-0117",
    address: "3891 Ranchview Richardson,California",
    status: "Active",
  },
  {
    name: "Brooklyn Simmons",
    gender: "M",
    age: 36,
    blood: "O+",
    diagnosis: "Hepatitis B",
    phone: "(316) 555-0116",
    address: "3891 Ranchview Richardson,California",
    status: "Passaway",
  },
  {
    name: "Jacob Jones",
    gender: "M",
    age: 36,
    blood: "O-",
    diagnosis: "Hepatitis B",
    phone: "(702) 555-0122",
    address: "3891 Ranchview Richardson,California",
    status: "Active",
  },
  {
    name: "Annette Black",
    gender: "F",
    age: 36,
    blood: "O-",
    diagnosis: "Hepatitis B",
    phone: "(319) 555-0115",
    address: "3891 Ranchview Richardson,California",
    status: "Active",
  },
  {
    name: "Annette Black",
    gender: "F",
    age: 36,
    blood: "O-",
    diagnosis: "Hepatitis B",
    phone: "(319) 555-0115",
    address: "3891 Ranchview Richardson,California",
    status: "Active",
  },
  {
    name: "Annette Black",
    gender: "F",
    age: 36,
    blood: "O-",
    diagnosis: "Hepatitis B",
    phone: "(319) 555-0115",
    address: "3891 Ranchview Richardson,California",
    status: "Active",
  },
  {
    name: "Annette Black",
    gender: "F",
    age: 36,
    blood: "O-",
    diagnosis: "Hepatitis B",
    phone: "(319) 555-0115",
    address: "3891 Ranchview Richardson,California",
    status: "Active",
  },
  {
    name: "Annette Black",
    gender: "F",
    age: 36,
    blood: "O-",
    diagnosis: "Hepatitis B",
    phone: "(319) 555-0115",
    address: "3891 Ranchview Richardson,California",
    status: "Active",
  },
];

//data for ASSIGNED TASK

export const TASK = [
  {
    id: 1,
    title: "Prepare patient for surgery",
    time: "12:30 AM",
    completed: false,
  },
  {
    id: 2,
    title: "Administer medication to Room 203",
    time: "12:30 AM",
    completed: false,
  },
  {
    id: 3,
    title: "Check vitals for Patient A",
    time: "12:30 AM",
    completed: false,
  },
  {
    id: 4,
    title: "Prepare patient for surgery",
    time: "12:30 AM",
    completed: false,
  },
  {
    id: 5,
    title: "Prepare patient for surgery",
    time: "12:30 AM",
    completed: false,
  },
  {
    id: 6,
    title: "Prepare patient for surgery",
    time: "12:30 AM",
    completed: false,
  },
  {
    id: 7,
    title: "Prepare patient for surgery",
    time: "12:30 AM",
    completed: false,
  },
  {
    id: 8,
    title: "Prepare patient for surgery",
    time: "12:30 AM",
    completed: false,
  },
  {
    id: 9,
    title: "Prepare patient for surgery",
    time: "12:30 AM",
    completed: false,
  },
];

export const Appointments = [
  {
    id: 1,
    patientName: "Jane Cooper",
    date: "12/06/21",
    time: "10:00am",
    type: "Delivery",
    status: "Active",
  },
  {
    id: 2,
    patientName: "Jane Cooper",
    date: "12/06/21",
    time: "11:00am",
    type: "Surgery",
    status: "Active",
  },
  {
    id: 3,
    patientName: "Jane Cooper",
    date: "12/06/21",
    time: "12:00pm",
    type: "Consultation",
    status: "Not Urgent",
  },
  {
    id: 4,
    patientName: "Jane Cooper",
    date: "12/06/21",
    time: "1:00pm",
    type: "Surgery",
    status: "Active",
  },
  {
    id: 5,
    patientName: "Jane Cooper",
    date: "12/06/21",
    time: "2:00pm",
    type: "Consultation",
    status: "Active",
  },
  {
    id: 6,
    patientName: "Jane Cooper",
    date: "12/06/21",
    time: "3:00pm",
    type: "Surgery",
    status: "Active",
  },
  {
    id: 7,
    patientName: "Jane Cooper",
    date: "12/06/21",
    time: "4:00pm",
    type: "Consultation",
    status: "Active",
  },
  {
    id: 8,
    patientName: "Jane Cooper",
    date: "12/06/21",
    time: "5:00pm",
    type: "injection",
    status: "Active",
  },
  {
    id: 7,
    patientName: "Jane Cooper",
    date: "12/06/21",
    time: "4:00pm",
    type: "Consultation",
    status: "Active",
  },
];

import mrStephen from "./src/assets/images/mrStephen.jpg";
import mrsYusuf from "./src/assets/images/mrsYusuf.jpg";
import mrsIbrahim from "./src/assets/images/mrsIbrahim.jpg";

export const listOfStaffs = [
  {
    image: mrStephen,
    name: "Esther Howard",
    role: "Nurse",
    gender: "Female",
    dob: "9/8/16",
    address: "4517 Washington Ave. Manchester, Kentucky 39495",
    email: "Omotolanifolashade9@gmail.com",
    MaritalStatus: "Married",
    stateOfOrigin: "Ogun State",
  },
  {
    image: mrsYusuf,
    name: "Esther Howard",
    role: "Nurse",
    gender: "Female",
    dob: "9/8/16",
    address: "4517 Washington Ave. Manchester, Kentucky 39495",
    email: "Omotolanifolashade9@gmail.com",
    MaritalStatus: "Married",
    stateOfOrigin: "Ogun State",
  },
  {
    image: mrsIbrahim,
    name: "Esther Howard",
    role: "Nurse",
    gender: "Female",
    dob: "9/8/16",
    address: "4517 Washington Ave. Manchester, Kentucky 39495",
    email: "Omotolanifolashade9@gmail.com",
    MaritalStatus: "Married",
    stateOfOrigin: "Ogun State",
  },
];

import users from "./src/assets/images/users.png";

export const incomingUpdate = [
  {
    img: users,
    notifications: "Today's Appointments",
    data: "12",
  },
  {
    img: users,
    notifications: "Pending Lab Results",
    data: "12",
  },
  {
    img: users,
    notifications: "Total Patients Discharged",
    data: "12",
  },
];

export const upComingAppointments = [
  {
    time: "09:00 AM",
    patientName: "Cameron Williamson",
    AppointmentsType: "Delivery",
    status: "Active",
  },
  {
    time: "09:00 AM",
    patientName: "Cameron Williamson",
    AppointmentsType: "Delivery",
    status: "Active",
  },
  {
    time: "09:00 AM",
    patientName: "Cameron Williamson",
    AppointmentsType: "Delivery",
    status: "Active",
  },
  {
    time: "09:00 AM",
    patientName: "Cameron Williamson",
    AppointmentsType: "Delivery",
    status: "Active",
  },
  {
    time: "09:00 AM",
    patientName: "Cameron Williamson",
    AppointmentsType: "Delivery",
    status: "Active",
  },
  {
    time: "09:00 AM",
    patientName: "Cameron Williamson",
    AppointmentsType: "Delivery",
    status: "Active",
  },
];

import incomingLogo from "./src/assets/images/incomingLogo.jpg";

export const incomingFromDoctor = [
  {
    sentBy: "Nurse",
    img: incomingLogo,
    name: "Leslie Alexander",
    patientId: "P-2025-002",
    insurance: "Self Pay",
    Registered: "09:05Am",
    paymentDetails: "View Patient Payment Details",
  },
  {
    sentBy: "Nurse",
    img: incomingLogo,
    name: "Leslie Alexander",
    patientId: "P-2025-002",
    insurance: "Self Pay",
    Registered: "09:05Am",
    paymentDetails: "View Patient Payment Details",
  },
  {
    sentBy: "Front Desk",
    img: incomingLogo,
    name: "Leslie Alexander",
    patientId: "P-2025-002",
    insurance: "Self Pay",
    Registered: "09:05Am",
    paymentDetails: "View Patient Payment Details",
  },
  {
    sentBy: "Front Desk",
    img: incomingLogo,
    name: "Leslie Alexander",
    patientId: "P-2025-002",
    insurance: "Self Pay",
    Registered: "09:05Am",
    paymentDetails: "View Patient Payment Details",
  },
  {
    sentBy: "Nurse",
    img: incomingLogo,
    name: "Leslie Alexander",
    patientId: "P-2025-002",
    insurance: "Self Pay",
    Registered: "09:05Am",
    paymentDetails: "View Patient Payment Details",
  },
  {
    sentBy: "Nurse",
    img: incomingLogo,
    name: "Leslie Alexander",
    patientId: "P-2025-002",
    insurance: "Self Pay",
    Registered: "09:05Am",
    paymentDetails: "View Patient Payment Details",
  },
];

export const appointmentsWithDoctor = [
  {
    header: "Today’s Appointment",
    value: "30",
    status: "Confirmed",
  },
  {
    header: "Pending",
    value: "2",
    status: "Awaiting Confirmation",
  },
  {
    header: "Today’s Appointment",
    value: "5",
    status: "Ready To Proceed",
  },
  {
    header: "Cancelled",
    value: "2",
    status: "Cancelled Today",
  },
];

export const doctorsAppointmentsPatients = [
  {
    name: "Jane Cooper",
    date: "7/18/17",
    Time: "09:00 AM",
    purpose: "Stomach Ulcer",
    status: "Not Urgent",
  },
  {
    name: "Jane Cooper",
    date: "7/18/17",
    Time: "09:00 AM",
    purpose: "Stomach Ulcer",
    status: "Not Urgent",
  },
  {
    name: "Jane Cooper",
    date: "7/18/17",
    Time: "09:00 AM",
    purpose: "Stomach Ulcer",
    status: "Not Urgent",
  },
  {
    name: "Jane Cooper",
    date: "7/18/17",
    Time: "09:00 AM",
    purpose: "Stomach Ulcer",
    status: "Emergency",
  },
  {
    name: "Jane Cooper",
    date: "7/18/17",
    Time: "09:00 AM",
    purpose: "Stomach Ulcer",
    status: "Not Urgent",
  },
];

export const resultLab = [
  {
    labId: "LR-2024-001",
    patientName: "Emma Williams",
    patientId: "PT-1234",
    testType: "Complete Blood Count",
    date: "2024-10-07",
    time: "09:30 AM",
    doctor: "Dr. Folake",
    status: "Completed",
  },

  {
    labId: "LR-2024-001",
    patientName: "Sarah Johnson",
    patientId: "PT-1234",
    testType: "HbA1c Test",
    date: "2024-10-07",
    time: "09:30 AM",
    doctor: "Dr. Folake",
    status: "Completed",
  },
  {
    labId: "LR-2024-001",
    patientName: "Sarah Johnson",
    patientId: "PT-1234",
    testType: "Complete Blood Count",
    date: "2024-10-07",
    time: "09:30 AM",
    doctor: "Dr. Folake",
    status: "Processing",
  },
  {
    labId: "LR-2024-001",
    patientName: "Sarah Johnson",
    patientId: "PT-1234",
    testType: "Complete Blood Count",
    date: "2024-10-07",
    time: "09:30 AM",
    doctor: "Dr. Folake",
    status: "Processing",
  },
  {
    labId: "LR-2024-001",
    patientName: "Sarah Johnson",
    patientId: "PT-1234",
    testType: "Complete Blood Count",
    date: "2024-10-07",
    time: "09:30 AM",
    doctor: "Dr. Folake",
    status: "Processing",
  },
  {
    labId: "LR-2024-001",
    patientName: "Sarah Johnson",
    patientId: "PT-1234",
    testType: "Complete Blood Count",
    date: "2024-10-07",
    time: "09:30 AM",
    doctor: "Dr. Folake",
    status: "Processing",
  },
  {
    labId: "LR-2024-001",
    patientName: "Sarah Johnson",
    patientId: "PT-1234",
    testType: "Complete Blood Count",
    date: "2024-10-07",
    time: "09:30 AM",
    doctor: "Dr. Folake",
    status: "Processing",
  },
  {
    labId: "LR-2024-001",
    patientName: "Sarah Johnson",
    patientId: "PT-1234",
    testType: "Complete Blood Count",
    date: "2024-10-07",
    time: "09:30 AM",
    doctor: "Dr. Folake",
    status: "Processing",
  },
  {
    labId: "LR-2024-001",
    patientName: "Sarah Johnson",
    patientId: "PT-1234",
    testType: "Complete Blood Count",
    date: "2024-10-07",
    time: "09:30 AM",
    doctor: "Dr. Folake",
    status: "Processing",
  },
  {
    labId: "LR-2024-001",
    patientName: "Sarah Johnson",
    patientId: "PT-1234",
    testType: "Complete Blood Count",
    date: "2024-10-07",
    time: "09:30 AM",
    doctor: "Dr. Folake",
    status: "Processing",
  },
  {
    labId: "LR-2024-001",
    patientName: "Sarah Johnson",
    patientId: "PT-1234",
    testType: "Complete Blood Count",
    date: "2024-10-07",
    time: "09:30 AM",
    doctor: "Dr. Folake",
    status: "Processing",
  },
  {
    labId: "LR-2024-001",
    patientName: "Sarah Johnson",
    patientId: "PT-1234",
    testType: "Complete Blood Count",
    date: "2024-10-07",
    time: "09:30 AM",
    doctor: "Dr. Folake",
    status: "Processing",
  },
  {
    labId: "LR-2024-001",
    patientName: "Sarah Johnson",
    patientId: "PT-1234",
    testType: "Complete Blood Count",
    date: "2024-10-07",
    time: "09:30 AM",
    doctor: "Dr. Folake",
    status: "Processing",
  },
  {
    labId: "LR-2024-001",
    patientName: "Sarah Johnson",
    patientId: "PT-1234",
    testType: "Complete Blood Count",
    date: "2024-10-07",
    time: "09:30 AM",
    doctor: "Dr. Folake",
    status: "Processing",
  },
  {
    labId: "LR-2024-001",
    patientName: "Sarah Johnson",
    patientId: "PT-1234",
    testType: "Complete Blood Count",
    date: "2024-10-07",
    time: "09:30 AM",
    doctor: "Dr. Folake",
    status: "Processing",
  },
  {
    labId: "LR-2024-001",
    patientName: "Sarah Johnson",
    patientId: "PT-1234",
    testType: "Complete Blood Count",
    date: "2024-10-07",
    time: "09:30 AM",
    doctor: "Dr. Folake",
    status: "Processing",
  },
  {
    labId: "LR-2024-001",
    patientName: "Sarah Johnson",
    patientId: "PT-1234",
    testType: "Complete Blood Count",
    date: "2024-10-07",
    time: "09:30 AM",
    doctor: "Dr. Folake",
    status: "Processing",
  },
  {
    labId: "LR-2024-001",
    patientName: "Sarah Johnson",
    patientId: "PT-1234",
    testType: "Complete Blood Count",
    date: "2024-10-07",
    time: "09:30 AM",
    doctor: "Dr. Folake",
    status: "Processing",
  },
];

import incomingAvatar from "./src/assets/images/incomingLogo.jpg";
export const doctorIncomingPatientDetails = [
  {
    image: incomingAvatar,
    patientName: "Leslie Alexander",
    gender: "Female",
    phoneNumber: "07037794935",
    patientId: "P-2025-002",
    insurance: "MedCare HMO",
    status: "Active",
  },
];

export const additionalInformation = [
  {
    bloodGroup: "A+",
    genotype: "AA",
    bloodGroup: "A+",
    lastVisit: "12:00 04/16/25",
  },
];

export const medicalHistory = [
  {
    type: "Consultation",
    diagnosis: "Hypertension check-up",
    time: "10:15 AM",
    date: "2024-11-15",
    notes: "BP elevated, mild headache",
    detailsLink: "View Details",
  },
  {
    type: "Consultation",
    diagnosis: "Hypertension check-up",
    time: "10:15 AM",
    date: "2024-11-15",
    notes: "BP elevated, mild headache",
    detailsLink: "View Details",
  },
  {
    type: "Consultation",
    diagnosis: "Hypertension check-up",
    time: "10:15 AM",
    date: "2024-11-15",
    notes: "BP elevated, mild headache",
    detailsLink: "View Details",
  },
  {
    type: "Consultation",
    diagnosis: "Hypertension check-up",
    time: "10:15 AM",
    date: "2024-11-15",
    notes: "BP elevated, mild headache",
    detailsLink: "View Details",
  },
  {
    type: "Consultation",
    diagnosis: "Hypertension check-up",
    time: "10:15 AM",
    date: "2024-11-15",
    notes: "BP elevated, mild headache",
    detailsLink: "View Details",
  },
];

export const currentVitals = [
  {
    patientName: "Leslie Alexander",
    ward: "Ward 3",
    bed: "Bed 10",
    lastUpdated: "5 mins ago",
  },
];

import heart from "./src/assets/images/heart.png";
import vitalSigns from "./src/assets/images/vitalSigns.png";
import oxygen from "./src/assets/images/oxygen.png";
import thermometer from "./src/assets/images/thermometer.png";
import schedule from "./src/assets/images/schedule.png";

export const moreVitals = [
  {
    image: heart,
    heading: "heartRate",
    heartRate: "78",
    value: "bpm",
  },
  {
    image: heart,
    beatsPerMinutes: "bpm",
    heading: "Blood Pressure",
    heartRate: "125/82",
    value: "bpm",
  },
  {
    image: oxygen,
    heading: "Oxygen",
    heartRate: "125/82",
    value: "%",
  },
  {
    image: thermometer,
    heading: "Temperature",
    heartRate: "98.6",
    value: "°F",
  },
  {
    image: vitalSigns,
    heading: "Respiratory",
    heartRate: "16",
    value: "rpm",
  },
  {
    image: schedule,
    heading: "Last Updated",
    heartRate: "10",
    value: "minutes ago",
  },
];

export const diagnosis = [
  {
    type: "Consultation",
    diagnosis: "Hypertension check-up",
    Allergies: "Hypertension check-up",
    Admission: "Consultation",
    date: "01/01/01",
  },
];

export const billing = [
  {
    name: "General Consultation",
    qty: 1,
    service: "General Consultation",
    price: 300000,
  },
  { name: "Malaria", qty: 1, service: "Lab Test", price: 300000 },
  {
    name: "General Consultation",
    qty: 1,
    service: "General Consultation",
    price: 300000,
  },
];

export const TestHistory = [
  {
    header: "Pending Test",
    value: "14",
    status: "+3 from yesterday",
  },
  {
    header: "Completed Today",
    value: "35",
    status: "On Track",
  },
  {
    header: "In Progress",
    value: "2",
    status: "3 urgent",
  },
  {
    header: "Low Stock Items",
    value: "7",
    status: "Needed Attention",
  },
];

export const pendingTestRequest = [
  {
    name: "John Doe",
    issuedBy: "Doctor",
    status: "Pending",
  },
  {
    name: "Jane Smith",
    issuedBy: "Doctor",
    status: "Pending",
  },
  {
    name: "Sarah Owolabi",
    issuedBy: "Doctor",
    status: "Pending",
  },
  {
    name: "Micheal Brown",
    issuedBy: "Doctor",
    status: "Pending",
  },
];

export const completedToday = [
  {
    name: "John Doe",
    testType: "Blood Test",
    date: "09:30 AM",
  },
  {
    name: "Jane Smith",
    testType: "Urine Test",
    date: "10:30 AM",
  },
  {
    name: "Maryam Aliyah",
    testType: "Pregnancy Test",
    date: "01:30 AM",
  },
  {
    name: "Adeboye David",
    testType: "x-ray",
    date: "03:30 AM",
  },
];

export const incomingTestResult = [
  {
    header: "New Request",
    value: "14",
  },
  {
    header: "Urgent Priority",
    value: "4",
  },
  {
    header: "High Priority",
    value: "2",
  },
  {
    header: "Avg. Wait time",
    value: "20 mm",
  },
];

export const patientTestResults = [
  {
    name: "John Doe",
    userId: "PT-2025-001",
    status: "Urgent",
    test: "Complete Blood Count (CBC)",
    date: "2025-10-09",
    requestedBy: "Dr. Alexa Mary",
    time: "Time: 08:30AM",
    symptoms: "Fever, fatigue, dizziness",
  },
  {
    name: "John Doe",
    userId: "PT-2025-001",
    status: "Urgent",
    test: "Complete Blood Count (CBC)",
    date: "2025-10-09",
    requestedBy: "Dr. Alexa Mary",
    time: "Time: 08:30AM",
    symptoms: "Fever, fatigue, dizziness",
  },
  {
    name: "John Doe",
    userId: "PT-2025-001",
    status: "Normal",
    test: "Complete Blood Count (CBC)",
    date: "2025-10-09",
    requestedBy: "Dr. Alexa Mary",
    time: "Time: 08:30AM",
    symptoms: "Fever, fatigue, dizziness",
  },
  {
    name: "John Doe",
    userId: "PT-2025-001",
    status: "Normal",
    test: "X-ray",
    date: "2025-10-09",
    requestedBy: "Dr. Alexa Mary",
    time: "Time: 08:30AM",
    symptoms: "Fever, fatigue, dizziness",
  },
];

export const stocks = [
  {
    header: "Total Items",
    value: "14",
    status: "Across all items",
  },
  {
    header: "Critical Stock",
    value: "4",
    status: "immediate action needed",
  },
  {
    header: "Low Stock",
    value: "3",
    status: "Re order soon",
  },
  {
    header: "Well stocked",
    value: "67",
    status: "Adequate supply",
  },
];

