// Centralized patient status constants matching backend enum values
// keep property names uppercase for easier reference, values are the strings
// the API expects lowercase underscore values so we mirror that.

export const PATIENT_STATUS = {
  REGISTERED: "registered",
  AWAITING_FRONT_DESK: "awaiting_front_desk",
  AWAITING_PAYMENT: "awaiting_payment",
  AWAITING_VITALS: "awaiting_vitals",
  VITALS_COMPLETED: "vitals_completed",
  AWAITING_CONSULTATION: "awaiting_consultation",
  AWAITING_DOCTOR: "awaiting_doctor",
  IN_CONSULTATION: "in_consultation",
  CONSULTATION_COMPLETED: "consultation_completed",
  AWAITING_SAMPLING: "awaiting_sampling",
  SAMPLING_COMPLETED: "sampling_completed",
  AWAITING_REVIEW: "awaiting_review",
  REVIEW_COMPLETED: "review_completed",
  AWAITING_INJECTION: "awaiting_injection",
  INJECTION_COMPLETED: "injection_completed",
  AWAITING_CASHIER: "awaiting_cashier",
  PAYMENT_COMPLETED: "payment_completed",
  AWAITING_NURSE: "awaiting_nurse",
  AWAITING_LAB: "awaiting_lab",
  LAB_IN_PROGRESS: "lab_in_progress",
  LAB_COMPLETED: "lab_completed",
  AWAITING_RADIOLOGY: "awaiting_radiology",
  RADIOLOGY_IN_PROGRESS: "radiology_in_progress",
  RADIOLOGY_COMPLETED: "radiology_completed",
  AWAITING_PHARMACY: "awaiting_pharmacy",
  PHARMACY_COMPLETED: "pharmacy_completed",
  AWAITING_ADMISSION: "awaiting_admission",
  ADMITTED: "admitted",
  UNDER_OBSERVATION: "under_observation",
  AWAITING_SURGERY: "awaiting_surgery",
  SURGERY_IN_PROGRESS: "surgery_in_progress",
  POST_SURGERY_RECOVERY: "post_surgery_recovery",
  POST_SURGERY_OBSERVATION: "post_surgery_observation",
  SURGERY_COMPLETED: "surgery_completed",
  TRANSFERRED: "transferred",
  REFERRED: "referred",
  ISOLATED: "isolated",
  AWAITING_DISCHARGE_APPROVAL: "awaiting_discharge_approval",
  DISCHARGE_IN_PROGRESS: "discharge_in_progress",
  DISCHARGED: "discharged",
  AWAITING_FOLLOW_UP: "awaiting_follow_up",
  FOLLOW_UP_COMPLETED: "follow_up_completed",
  DECEASED: "deceased",
  NO_SHOW: "no_show",
  CANCELLED: "cancelled",
  COMPLETED: "completed",
};
